name: cake_shop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  fluttertoast: ^8.2.2
  flutter_dotenv: ^5.1.0
  intl_phone_field: ^3.1.0
  razorpay_flutter: ^1.4.0
  flutter_inappwebview: ^6.0.0
  universal_html: ^2.0.6
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/bakery_bg.jpg
    - assets/images/cake-1.webp
    - assets/images/cake-2.webp
    - assets/images/placeholder.jpg
    - assets/razorpay_checkout.html